import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FontAwesomeConfig from './fontawesome';
import { GlobalProvider } from "./context";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

        <head>
        <FontAwesomeConfig></FontAwesomeConfig>
        </head>
      <body className={inter.className}>
        <GlobalProvider>
          {children}
        </GlobalProvider>
        </body>
    </html>
  );
}
